#!/bin/bash
###############################################################################
# Clash Monitor 周报生成与发送
#
# 功能：汇总过去 7 天的健康检查数据，生成周报并发送到 Gmail
# 用法：bash scripts/weekly_report.sh [--dry-run]
###############################################################################

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${STATE_DIR:-$PROJECT_ROOT/data/state}"
NODE_STATE_FILE="$STATE_DIR/node_state.json"
CIRCUIT_BREAKER_FILE="$STATE_DIR/circuit_breaker.json"
LOG_FILE="${LOG_FILE:-$PROJECT_ROOT/logs/clash_health.log}"
LOG_ARCHIVE_DIR="$PROJECT_ROOT/logs/archive"

# 收件人
REPORT_TO="${REPORT_TO:-jason6666@gmail.com}"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# ==================== 数据收集 ====================

collect_weekly_data() {
    local total_checks=0 total_healthy=0
    local total_vpn=0 total_cf=0 total_api=0 total_local=0 total_slow=0
    local total_switches=0 total_cbs=0
    local days_with_data=0
    local daily_details=""

    for i in $(seq 0 6); do
        local d
        d=$(date -v-${i}d '+%Y-%m-%d' 2>/dev/null || date -d "${i} days ago" '+%Y-%m-%d' 2>/dev/null)
        local sf="$STATE_DIR/stats_${d}.json"

        if [[ -f "$sf" ]]; then
            days_with_data=$((days_with_data + 1))
            local checks healthy vpn cf api local_f slow switches cbs pct
            checks=$(jq -r '.checks // 0' "$sf")
            healthy=$(jq -r '.healthy // 0' "$sf")
            vpn=$(jq -r '.faults.vpn // 0' "$sf")
            cf=$(jq -r '.faults.cf // 0' "$sf")
            api=$(jq -r '.faults.api // 0' "$sf")
            local_f=$(jq -r '.faults.local // 0' "$sf")
            slow=$(jq -r '.faults.slow // 0' "$sf")
            switches=$(jq -r '.switches // 0' "$sf")
            cbs=$(jq -r '.circuit_breaks // 0' "$sf")

            total_checks=$((total_checks + checks))
            total_healthy=$((total_healthy + healthy))
            total_vpn=$((total_vpn + vpn))
            total_cf=$((total_cf + cf))
            total_api=$((total_api + api))
            total_local=$((total_local + local_f))
            total_slow=$((total_slow + slow))
            total_switches=$((total_switches + switches))
            total_cbs=$((total_cbs + cbs))

            pct=0
            (( checks > 0 )) && pct=$((healthy * 100 / checks))
            local faults=$((vpn + cf + api + local_f + slow))
            daily_details+="  ${d}  检查:${checks}  健康:${healthy}  故障:${faults}  可用率:${pct}%"
            if (( switches > 0 )); then
                daily_details+="  切换:${switches}"
            fi
            if (( slow > 0 )); then
                daily_details+="  慢速:${slow}"
            fi
            daily_details+=$'\n'
        fi
    done

    # 总可用率
    local total_pct=0
    (( total_checks > 0 )) && total_pct=$((total_healthy * 100 / total_checks))
    local total_faults=$((total_vpn + total_cf + total_api + total_local + total_slow))

    # 当前状态
    local current_node="未知" ok_count=0 switch_count=0
    if [[ -f "$NODE_STATE_FILE" ]]; then
        current_node=$(jq -r '.last_node // "未知"' "$NODE_STATE_FILE")
        ok_count=$(jq -r '.health_ok_count // 0' "$NODE_STATE_FILE")
        switch_count=$(jq -r '.switch_count // 0' "$NODE_STATE_FILE")
    fi

    local cb_status="🟢 正常"
    if [[ -f "$CIRCUIT_BREAKER_FILE" ]]; then
        local opened
        opened=$(jq -r '.opened_at // 0' "$CIRCUIT_BREAKER_FILE")
        [[ "$opened" -gt 0 ]] && cb_status="🔴 已触发"
    fi

    # 最近异常
    local recent_errors=""
    if [[ -f "$LOG_FILE" ]]; then
        recent_errors=$(grep -E '\[(WARN|ERROR)\]' "$LOG_FILE" \
            | grep -v '防抖\|改善不足\|驻留未满\|跳过\|未配置' \
            | tail -10 || true)
    fi

    # 周报起止日期
    local week_start week_end
    week_start=$(date -v-6d '+%Y-%m-%d' 2>/dev/null || date -d '6 days ago' '+%Y-%m-%d')
    week_end=$(date '+%Y-%m-%d')

    # 生成报告
    cat <<REPORT
═══════════════════════════════════════════════
  Clash VPN Monitor 周报
  ${week_start} ~ ${week_end}
═══════════════════════════════════════════════

📊 周汇总
  总检查次数:   ${total_checks}
  总健康次数:   ${total_healthy}
  总故障次数:   ${total_faults}
  周可用率:     ${total_pct}%
  节点切换:     ${total_switches} 次
  熔断触发:     ${total_cbs} 次

📋 故障明细
  VPN/节点故障:  ${total_vpn}
  Cloudflare:    ${total_cf}
  上游API故障:   ${total_api}
  本地网络故障:  ${total_local}
  慢速降级:      ${total_slow}

📅 每日明细（${days_with_data} 天有数据）
${daily_details}
📍 当前状态
  当前节点:      ${current_node}
  累计健康检查:  ${ok_count} 次
  累计节点切换:  ${switch_count} 次
  熔断状态:      ${cb_status}

⚠️ 最近异常（最多 10 条）
${recent_errors:-  (无异常记录 ✅)}

═══════════════════════════════════════════════
  Generated by Clash Monitor · $(date '+%Y-%m-%d %H:%M:%S')
═══════════════════════════════════════════════
REPORT
}

# ==================== 发送 ====================

send_report() {
    local report="$1"
    local week_start week_end
    week_start=$(date -v-6d '+%Y-%m-%d' 2>/dev/null || date -d '6 days ago' '+%Y-%m-%d')
    week_end=$(date '+%Y-%m-%d')
    local subject="[Clash Monitor 周报] ${week_start} ~ ${week_end}"

    if [[ "$DRY_RUN" == true ]]; then
        echo "$report"
        echo ""
        echo "--- DRY-RUN: 以上报告将发送到 $REPORT_TO ---"
        return 0
    fi

    # 用 Gmail API 发送
    local send_script="$HOME/clawd/projects/gmail-tools/src/send_gmail_api.py"
    if [[ -f "$send_script" ]]; then
        python3 "$send_script" "$REPORT_TO" "$subject" "$report"
        echo "✅ 周报已发送到 $REPORT_TO"
    else
        echo "❌ Gmail 发送脚本不存在: $send_script"
        exit 1
    fi
}

# ==================== 主逻辑 ====================

main() {
    local report
    report=$(collect_weekly_data)
    send_report "$report"
}

main "$@"
